# Generated by Django 2.1.5 on 2019-03-25 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190325_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dept_head',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
