# Generated by Django 2.1.5 on 2019-03-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190325_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountprofile',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='dept_head',
        ),
        migrations.AddField(
            model_name='dept',
            name='account',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='account.AccountProfile'),
        ),
    ]
