# Generated by Django 2.1.5 on 2019-03-27 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_auto_20190327_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='account',
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='dept',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Dept'),
        ),
        migrations.AddField(
            model_name='dept',
            name='dept_head',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
