# Generated by Django 2.1.5 on 2019-03-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190327_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='phone_num',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dept',
            name='dept_name',
            field=models.CharField(choices=[('Vis', 'Vis'), ('Sound', 'Sound'), ('Lighting', 'Lighting'), ('Transmission', 'Transmission'), ('Admin', 'Administration'), ('edt', 'Editing')], max_length=20),
        ),
    ]
