# Generated by Django 2.1.5 on 2019-03-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190327_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='employee_status',
            field=models.BooleanField(default=True),
        ),
    ]
