# Generated by Django 2.1.5 on 2019-03-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_accountprofile_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountprofile',
            name='employee_status',
        ),
        migrations.RemoveField(
            model_name='accountprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='accountprofile',
            name='last_name',
        ),
    ]
