# Generated by Django 2.1.5 on 2019-03-31 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190330_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Dept'),
        ),
    ]
