# Generated by Django 2.1.5 on 2019-02-24 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_barcode', models.CharField(default='', max_length=20)),
                ('item_name', models.CharField(default='', max_length=200)),
                ('item_type', models.CharField(default='', max_length=200)),
                ('item_dept', models.CharField(default='', max_length=200)),
                ('current_employee', models.CharField(default='', max_length=20)),
                ('item_amount', models.IntegerField()),
                ('item_description', models.CharField(default='', max_length=500)),
                ('item_notes', models.CharField(default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccountProfile')),
            ],
        ),
    ]
