# Generated by Django 2.1.5 on 2019-03-31 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_auto_20190325_0015'),
        ('account', '0010_auto_20190331_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(default='', max_length=50)),
                ('job_start_date', models.DateField()),
                ('job_end_date', models.DateField()),
                ('get_in_time', models.TimeField()),
                ('job_manager', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.AccountProfile')),
            ],
        ),
        migrations.CreateModel(
            name='JobItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ManyToManyField(to='item.Items')),
                ('job_id', models.ManyToManyField(to='job.Job')),
            ],
        ),
    ]
