# Generated by Django 2.1.5 on 2019-04-01 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20190325_0015'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='items',
            field=models.ManyToManyField(related_name='all_items', through='job.JobItems', to='item.Items'),
        ),
        migrations.RemoveField(
            model_name='jobitems',
            name='item_id',
        ),
        migrations.AddField(
            model_name='jobitems',
            name='item_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jobItems', to='item.Items'),
        ),
        migrations.RemoveField(
            model_name='jobitems',
            name='job_id',
        ),
        migrations.AddField(
            model_name='jobitems',
            name='job_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jobItems', to='job.Job'),
        ),
    ]
